CREATE DATABASE bai1;
USE bai1;
CREATE TABLE Class(
id INT PRIMARY KEY NOT NULL,
name VARCHAR(20)
);
CREATE TABLE Teacher(
id INT PRIMARY KEY NOT NULL,
name VARCHAR(20),
age INT,
country VARCHAR(50)
);